#spring:
#  datasource:
#    url: jdbc:mysql://172.17.0.171:3306/windhp_hospital?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
#    username: demo
#    password: demo
