#spring:
#  datasource:
#    url: jdbc:mysql://172.16.9.143:7103/windhp_hospital?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
#    username: demo
#    password: demo