#spring:
#  datasource:
#    url: jdbc:mysql://172.16.30.143:3370/windhp_hospital?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
#    username: dev
#    password: 112233
#  jpa:
#    generate-ddl: true
#    hibernate.ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    database: mysql